+incdir+/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src

/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_cheriot_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_1p_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_2p_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_rom_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_1r1w_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_cipher_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_tracer_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_and2.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_buf.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_clock_buf.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_clock_gating.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_flop.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_flop_no_rst.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_usb_diff_rx.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_xnor2.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_xor2.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_pad_wrapper_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_22_16_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_22_16_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_28_22_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_28_22_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_39_32_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_39_32_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_64_57_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_64_57_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_72_64_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_72_64_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_22_16_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_22_16_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_39_32_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_39_32_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_72_64_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_72_64_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_76_68_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_hamming_76_68_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_22_16_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_22_16_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_28_22_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_28_22_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_39_32_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_39_32_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_64_57_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_64_57_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_72_64_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_72_64_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_22_16_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_22_16_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_39_32_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_39_32_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_72_64_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_72_64_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_76_68_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_secded_inv_hamming_76_68_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_icache.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_cdc_rand_delay.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_subst_perm.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_present.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_prince.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_count_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_count.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_clock_mux2.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_pad_attr.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_pad_wrapper.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_1p.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_1r1w.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_2p.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_rom.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_lfsr.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_sec_anchor_buf.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_sec_anchor_flop.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_util_pkg.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/stream_fork.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/stream_join_dynamic.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ram_1p.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ram_2p.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/bus.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/simulator_ctrl.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/timer.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_clock_inv.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_flop_2sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_flop_en.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi4_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi4_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi4_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi8_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi8_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi8_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi12_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi12_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi12_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi16_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi16_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi16_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi20_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi20_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi20_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi24_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi24_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi24_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi28_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi28_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi28_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi32_sender.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi32_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_mubi32_dec.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_onehot_enc.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_onehot_mux.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_1p_adv.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_cheriot_ex.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_alu.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_branch_predict.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_compressed_decoder.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_controller.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_cs_registers.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_csr.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_counter.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_decoder.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_ex_block.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_fetch_fifo.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_id_stage.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_if_stage.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_load_store_unit.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_multdiv_fast.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_multdiv_slow.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_prefetch_buffer.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_pmp.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_wb_stage.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_dummy_instr.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_core.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_fifo_async_sram_adapter.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_fifo_async_simple.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_fifo_async.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_fifo_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_fifo_sync_cnt.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_clock_div.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_rst_sync.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/prim_ram_1p_scr.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_register_file_ff.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_register_file_fpga.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_register_file_latch.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_trvk.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_lockstep.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_tracer.sv
/home/yellow/qnsc_usr7/QNSC_MCU_ws/IP/CPU/RTL/src/ibex_top.sv
